// Copies third-party runtime assets into showcase/assets/vendor so the site loads nothing from other origins.
// model-viewer and the Plex font come from the pinned npm packages; the Draco decoder is the version model-viewer
// downloads from gstatic by default. Re-run `npm run vendor` after changing a version, then update the paths in
// showcase/assets/showcase.js and showcase/assets/showcase.css.
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DRACO = '1.5.6';
const out = fileURLToPath(new URL('../showcase/assets/vendor/', import.meta.url));
const version = async name => JSON.parse(await readFile(`node_modules/${name}/package.json`, 'utf8')).version;
await mkdir(join(out, 'fonts'), { recursive: true });
await mkdir(join(out, `draco-${DRACO}`), { recursive: true });

const mv = await version('@google/model-viewer');
await copyFile('node_modules/@google/model-viewer/dist/model-viewer.min.js', join(out, `model-viewer-${mv}.min.js`));
await copyFile('node_modules/@google/model-viewer/LICENSE', join(out, 'LICENSE-Apache-2.0.txt'));
for (const w of [300, 400, 500, 600]) {
  await copyFile(`node_modules/@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-${w}-normal.woff2`, join(out, `fonts/ibm-plex-sans-latin-${w}.woff2`));
}
await copyFile('node_modules/@fontsource/ibm-plex-sans/LICENSE', join(out, 'LICENSE-IBM-Plex-Sans-OFL-1.1.txt'));
for (const file of ['draco_decoder.js', 'draco_decoder.wasm', 'draco_wasm_wrapper.js']) {
  const res = await fetch(`https://www.gstatic.com/draco/versioned/decoders/${DRACO}/${file}`);
  if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
  await writeFile(join(out, `draco-${DRACO}`, file), Buffer.from(await res.arrayBuffer()));
}

await writeFile(join(out, 'README.md'), `# Vendored third-party files

Generated by \`scripts/vendor-assets.mjs\` (\`npm run vendor\`). Do not edit by hand.

| File | Version | Licence | Source |
|---|---|---|---|
| \`model-viewer-${mv}.min.js\` | ${mv} | Apache-2.0 (\`LICENSE-Apache-2.0.txt\`) | npm \`@google/model-viewer\` |
| \`draco-${DRACO}/\` | ${DRACO} | Apache-2.0 (\`LICENSE-Apache-2.0.txt\`) | https://www.gstatic.com/draco/versioned/decoders/${DRACO}/ |
| \`fonts/ibm-plex-sans-latin-*.woff2\` | npm \`@fontsource/ibm-plex-sans\` ${await version('@fontsource/ibm-plex-sans')} | SIL OFL 1.1 (\`LICENSE-IBM-Plex-Sans-OFL-1.1.txt\`) | https://github.com/IBM/plex |
`);
console.log(`vendored model-viewer ${mv}, Draco ${DRACO}, IBM Plex Sans (4 weights)`);
